# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    my.oauth_aware.user_provider.service:
        class: AppBundle\Security\Core\User\MyCustomServerFOSUBUserProvider
        arguments:
            - '@fos_user.user_manager'
            - {my_custom_server: id}
            - '@doctrine'